class ExecutiveCompensation: ...
class ShareholderProposal: ...
class BoardMember: ...
class SayOnPayResult: ...
class ProxyData: ...

def parse_proxy(
    filing_html: str,
    accession_number: str,
    filing_date: str,
) -> ProxyData: ...
