from __future__ import annotations

from pathlib import Path
from types import ModuleType
from typing import Any

from pydantic import BaseModel

class XbrlExtensionError(RuntimeError): ...

class XbrlFact(BaseModel):
    tag: str
    namespace: str
    local_name: str
    value: float
    raw_value: str
    scale: int
    decimals: int | None
    unit: str | None
    context_ref: str
    period_start: str | None
    period_end: str | None
    period_instant: str | None
    entity_id: str | None
    segment: str | None

def _load_xbrl_module() -> ModuleType: ...
def _field(raw_fact: object, name: str) -> Any: ...
def _to_fact(raw_fact: object) -> XbrlFact: ...
def _to_facts(raw_facts: list[object]) -> list[XbrlFact]: ...

class XbrlParser:
    def __init__(self, module: ModuleType | None = ...) -> None: ...
    def parse_ixbrl(self, html: str) -> list[XbrlFact]: ...
    def parse_instance(self, xml: str) -> list[XbrlFact]: ...
    def parse_auto(self, content: str) -> list[XbrlFact]: ...
    def parse_file(self, path: str | Path) -> list[XbrlFact]: ...

def create_xbrl_parser() -> XbrlParser: ...
def extract_facts(content: str) -> list[XbrlFact]: ...
def extract_facts_from_file(path: str | Path) -> list[XbrlFact]: ...
