from dataclasses import dataclass, field

from langchain_core.documents import Document as Document

from sec_nlp.core.infra.logger import logger as logger

@dataclass(frozen=True)
class SimHashConfig:
    num_bits: int = ...
    max_distance: int = ...

@dataclass
class SimHashDeduplicator:
    config: SimHashConfig = field(default_factory=SimHashConfig)
    def __post_init__(self) -> None: ...
    def is_duplicate(self, text: str) -> bool: ...
    def add(self, text: str) -> int | None: ...
    def add_if_unique(self, text: str) -> tuple[bool, int | None]: ...
    def deduplicate_documents(self, docs: list[Document]) -> list[Document]: ...
    def reset(self) -> None: ...
    @property
    def count(self) -> int: ...
