__all__ = [
    "PipelineException",
    "InvalidEmailException",
    "InvalidSymbolException",
    "InvalidDateException",
    "InvalidPathException",
    "InvalidLLMException",
    "InvalidVectorException",
    "InsufficientDiskException",
    "LLMUnavailableException",
    "VectorUnavailableException",
    "MissingDependencyException",
    "IncompatibleDependencyException",
]

class PipelineException(Exception): ...
class InvalidEmailException(PipelineException): ...
class InvalidSymbolException(PipelineException): ...
class InvalidDateException(PipelineException): ...
class InvalidPathException(PipelineException): ...
class InvalidLLMException(PipelineException): ...
class InvalidVectorException(PipelineException): ...
class InsufficientDiskException(PipelineException): ...
class LLMUnavailableException(PipelineException): ...
class VectorUnavailableException(PipelineException): ...
class MissingDependencyException(PipelineException): ...
class IncompatibleDependencyException(PipelineException): ...
