# src/sec_nlp/pipelines/presets/analyze/types.py
"""Shared state and payload types for the analyze pipeline."""

from __future__ import annotations

import threading
from typing import TYPE_CHECKING, TypedDict

from sec_nlp.types import JsonDict

if TYPE_CHECKING:
    from langchain_core.documents import Document

    from .steps.search.efts_search import EFTSSearchResult

type Timings = dict[str, float]

# ---------------------------------------------------------------------------
# Graceful abort support
# ---------------------------------------------------------------------------
_abort_event = threading.Event()


def is_abort_requested() -> bool:
    """Check whether a graceful abort has been requested (Ctrl+C)."""
    return _abort_event.is_set()


class PrefetchedSymbolData(TypedDict):
    """Symbol-scoped data prepared in a background worker ahead of execution."""

    docs: list[Document]
    efts_ok: bool
    efts_results: list[EFTSSearchResult]
    relationships: JsonDict
    timings: Timings
    preprocessed: bool


class ChunkStats(TypedDict, total=False):
    """Chunk-level distribution metrics captured for a symbol run."""

    count: int
    min_value: float
    max_value: float
    median: float
    mean: float
    analyzed_count: int
    timings: Timings


class SymbolRunMetadata(TypedDict):
    """Per-symbol metadata generated by the analyze pipeline."""

    outputs: int
    chunk_stats: ChunkStats


type RunMetadata = dict[str, SymbolRunMetadata | int]
