from .conftest import DummyLLM as DummyLLM
from collections.abc import Callable as Callable

def test_llm_passthrough(dummy_llm: Callable[[bool], DummyLLM]) -> None: ...
def test_llm_generate(dummy_llm: Callable[[bool], DummyLLM]) -> None: ...
