fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: mixed-line-ending

# Python
- repo: local
  hooks:
  - id: py-lint
    name: Python Linting
    entry: make py-lint
    types: [python]
    language: system
    pass_filenames: false

  - id: py-types
    name: Python Typecheck (ty)
    entry: make py-types
    files: '^(src/|tests/).*\.py$'
    language: system
    pass_filenames: false

  - id: rs-m-fmt
    name: Rust Format (market)
    entry: make rs-m-fmt
    files: '^crates/market/'
    language: system
    pass_filenames: false

  - id: rs-m-clippy
    name: Rust Clippy (market)
    entry: make rs-m-clippy
    files: '^crates/market/'
    language: system
    pass_filenames: false

  - id: rs-sg-fmt
    name: Rust Format (efts)
    entry: make rs-sg-fmt
    files: '^crates/efts/'
    language: system
    pass_filenames: false

  - id: rs-sg-clippy
    name: Rust Clippy (efts)
    entry: make rs-sg-clippy
    files: '^crates/efts/'
    language: system
    pass_filenames: false
