[project]
name = "sec-nlp"
version = "0.1.0"
description = "Summarize SEC filings using local LLMs"
authors = [
  { name = "Nicolas Hill", email = "your-email@example.com" }
]
requires-python = "==3.11.3"
dependencies = [
  "python-dotenv",
  "tqdm",
  "transformers",
  "torch",
  "pydantic",
  "langchain",
  "langchain-core",
  "langchain-community",
  "langchain-text-splitters",
  "langchain-huggingface",
  "beautifulsoup4",
  "lxml",
  "markdownify",
  "huggingface_hub",
  "sec_edgar_downloader",
  "langchain-pinecone>=0.2.12",
  "pinecone>=7.3.0",
  "accelerate>=1.10.1",
  "pinecone-plugin-assistant>=1.8.0",
  "uuid>=1.30",
  "sentence-transformers>=5.1.0",
]

[project.scripts]
main = "sec_nlp.__main__:main"


[tool.setuptools]
packages = ["sec_nlp"]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
]
