[project]
name = "sec-nlp-pipeline"
version = "0.1.0"
description = "Summarize SEC filings using local LLMs"
authors = [
  { name = "Nicolas Hill", email = "your-email@example.com" }
]
dependencies = [
  "python-dotenv",
  "tqdm",
  "transformers",
  "torch",
  "pydantic",
  "langchain",
  "langchain-core",
  "langchain-community",
  "langchain-text-splitters",
  "langchain-huggingface",
  "beautifulsoup4",
  "lxml",
  "markdownify",
  "huggingface_hub"
]
requires-python = "=3.11"

[tool.setuptools]
packages = ["chains", "utils", "llms"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
