[project]
name = "sec-nlp"
version = "0.1.0"
description = "Summarize SEC filings using local LLMs"
authors = [
  { name = "Nicolas Hill", email = "your-email@example.com" }
]
requires-python = "==3.11.3"
dependencies = [
  "python-dotenv",
  "tqdm",
  "transformers",
  "torch",
  "pydantic",
  "langchain",
  "langchain-core",
  "langchain-community",
  "langchain-text-splitters",
  "langchain-huggingface",
  "beautifulsoup4",
  "lxml",
  "markdownify",
  "huggingface_hub",
  "sec_edgar_downloader",
  "langchain-pinecone>=0.2.12",
  "pinecone>=7.3.0",
  "accelerate>=1.10.1",
  "pinecone-plugin-assistant>=1.8.0",
  "uuid>=1.30",
  "sentence-transformers>=5.1.0",
]

[project.scripts]
cli = "sec_nlp.cli.__main__:main"

[tool.uv_build]
package = "sec_nlp"
src-dir = "src"
include = ["pyproject.toml", "README.md"]

[tool.setuptools.package-data]
sec_nlp = ["py.typed"]

[tool.mypy]
python_version = "3.11"
packages = ["sec_nlp"]
plugins = ["pydantic.mypy"]
mypy_path = ["src"]
strict = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
exclude = [
  '^dist/',
  '^src/sec_nlp/data/',
  '^src/sec_nlp/.*/__pycache__',
]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.autopep8]
recursive = true
in_place = false
max_line_length = 100
ignore = ["E203", "W503"]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "mypy",
  "autopep8",
  "pydantic",
  "python-dotenv",
  "tqdm",
  "pinecone-client>=5",
  "transformers",
  "torch",
  "langchain-core",
  "langchain-community",
  "langchain-text-splitters",
  "types-tqdm",
  "types-requests",
  "types-PyYAML",
]