[rules]
ambiguous-protocol-member = "error"
ignore-comment-unknown-rule = "error"
invalid-ignore-comment = "error"
possibly-missing-attribute = "error"
possibly-missing-implicit-call = "error"
redundant-cast = "error"
unresolved-global = "error"
unsupported-base = "error"

[analysis]
# Respect `type: ignore` comments (kept only for external modules).
respect-type-ignore-comments = true

[environment]
extra-paths = ["./src", "./tests", "./types"]
python-version = "3.13"

[src]
respect-ignore-files = false
