class EventHeadline: ...
class EventImpact: ...
class DetectedEvent: ...
class EventsResult: ...

class EventsSettings:
    pipeline_type: str

class EventsPipeline:
    pipeline_type: str
    config: EventsSettings
