class FilingEvent: ...
class NewsCluster: ...
class NewsCorrelation: ...
class NewsHeadline: ...
class NewsTimelineEntry: ...
class NewsResult: ...

class NewsSettings:
    pipeline_type: str

class NewsPipeline:
    pipeline_type: str
    config: NewsSettings
