import argparse
from _typeshed import Incomplete
from pathlib import Path
from sec_nlp.core import FilingMode as FilingMode, Pipeline as Pipeline, default_prompt_path as default_prompt_path, get_logger as get_logger, settings as settings, setup_logging as setup_logging

logger: Incomplete

def parse_args() -> argparse.Namespace: ...
def setup_folders(fresh: bool) -> tuple[Path, Path]: ...
def cleanup_downloads(downloads_folder: Path) -> None: ...
def main() -> None: ...
