[package]
name = "market"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "market"
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
pyo3 = { version = "0.28.2", features = ["extension-module", "abi3-py313"] }
pyo3-async-runtimes = { version = "0.28.0", features = ["tokio-runtime"] }
tokio = { version = "1.37", features = ["rt-multi-thread", "time", "sync"] }
yahoo_finance_api = "2.4"

[build-dependencies]
pyo3-build-config = "0.28.2"
