from pathlib import Path
from typing import Any

from _typeshed import Incomplete
from rich.progress import Progress

console: Incomplete

class CLIFormatter:
    @staticmethod
    def print_header(title: str, subtitle: str | None = None) -> None: ...
    @staticmethod
    def print_success(message: str) -> None: ...
    @staticmethod
    def print_error(message: str) -> None: ...
    @staticmethod
    def print_warning(message: str) -> None: ...
    @staticmethod
    def print_info(message: str) -> None: ...
    @staticmethod
    def print_config(config: dict[str, Any], title: str = "Configuration") -> None: ...
    @staticmethod
    def print_results(results: dict[str, list[Path]], elapsed: float) -> None: ...
    @staticmethod
    def print_file_tree(root: Path, title: str = "Files") -> None: ...
    @staticmethod
    def create_progress() -> Progress: ...

def format_size(size_bytes: int) -> str: ...

class InteractivePrompts:
    @staticmethod
    def confirm(message: str, default: bool = False) -> bool: ...
    @staticmethod
    def select(message: str, choices: list[str]) -> str: ...
    @staticmethod
    def text(message: str, default: str = "") -> str: ...
    @staticmethod
    def path(message: str, default: str = "", only_directories: bool = False) -> str: ...
    @staticmethod
    def select_symbols() -> list[str]: ...
    @staticmethod
    def select_date_range() -> tuple[str, str]: ...
