from pathlib import Path

from textual.containers import Horizontal, Vertical, VerticalScroll
from textual.widgets import Checkbox, Input, Select, Static

from sec_nlp.tui.interfaces import FormSpec, SectionSpec
from sec_nlp.tui.market import MarketSnapshot
from sec_nlp.tui.specs import SegmentSpec
from sec_nlp.types import ConfigScalar

type _FieldWidget = Input | Checkbox | Select

class Spinner(Static):
    def __init__(self) -> None: ...
    def on_mount(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class SegmentRow(Horizontal):
    def __init__(self, spec: SegmentSpec) -> None: ...
    @property
    def state(self) -> ConfigScalar: ...
    def set_state(self, state: ConfigScalar) -> None: ...
    def set_detail(self, detail: ConfigScalar | None) -> None: ...

class SegmentPanel(Vertical):
    def __init__(self) -> None: ...
    def load_segments(self, segments: tuple[SegmentSpec, ...]) -> None: ...
    def advance_to(
        self, index: int, detail: ConfigScalar | None = None
    ) -> None: ...
    def finish(self, success: bool) -> None: ...
    def reset(self) -> None: ...

class FieldRow(Horizontal):
    def __init__(
        self,
        label: ConfigScalar,
        widget: _FieldWidget,
        help_text: ConfigScalar | None,
    ) -> None: ...

class CollapsibleSection(Vertical):
    def __init__(
        self,
        section_spec: SectionSpec,
        rows: list[FieldRow],
        classes: ConfigScalar = ...,
    ) -> None: ...
    def toggle(self) -> None: ...
    @property
    def content(self) -> Vertical: ...

class FormView(VerticalScroll):
    def __init__(self) -> None: ...
    def set_form(self, form_spec: FormSpec) -> None: ...
    def focus_first(self) -> None: ...
    def focus_field(self, key: ConfigScalar) -> None: ...
    def get_values(self) -> dict[ConfigScalar, ConfigScalar]: ...
    def get_extra_args(self) -> ConfigScalar | None: ...

class MarketPanel(Vertical):
    def __init__(self, classes: ConfigScalar = ...) -> None: ...
    def set_snapshot(self, snapshot: MarketSnapshot | None) -> None: ...
    def set_message(self, message: ConfigScalar | None) -> None: ...
    def reset(self) -> None: ...

class ResultsPanel(Vertical):
    def __init__(self, classes: ConfigScalar = ...) -> None: ...
    def set_paths(self, paths: list[Path]) -> None: ...
