import pytest

class TestClient:
    def test_client_creation(self) -> None: ...
    def test_client_with_user_agent(self) -> None: ...
    def test_client_with_timeout(self) -> None: ...
    def test_fetch_text(self) -> None: ...
    def test_fetch_json(self) -> None: ...
    def test_fetch_invalid_domain_raises(self) -> None: ...
    def test_fetch_http_rejected(self) -> None: ...

class TestCIKTicker:
    def test_normalize_cik(self) -> None: ...
    def test_normalize_cik_with_prefix(self) -> None: ...
    def test_lookup_ticker(self) -> None: ...
    def test_lookup_ticker_case_insensitive(self) -> None: ...
    def test_lookup_invalid_ticker_raises(self) -> None: ...
    def test_get_all_tickers(self) -> None: ...
    def test_get_all_tickers_contains_major_stocks(self) -> None: ...

class TestCompanyData:
    def test_get_company_facts(self) -> None: ...
    def test_get_company_facts_has_taxonomies(self) -> None: ...
    def test_get_company_filings(self) -> None: ...
    def test_get_company_filings_recent(self) -> None: ...
    def test_get_company_invalid_cik_raises(self) -> None: ...

class TestParsers:
    def test_parse_html_doc(self) -> None: ...
    def test_parse_json_doc(self) -> None: ...
    def test_parse_document_auto_html(self) -> None: ...
    def test_parse_document_auto_json(self) -> None: ...
    def test_parse_document_auto_text(self) -> None: ...
    def test_parse_invalid_html_raises(self) -> None: ...
    def test_parse_invalid_json_raises(self) -> None: ...

class TestIntegration:
    @pytest.mark.slow
    def test_full_workflow(self) -> None: ...
    @pytest.mark.slow
    def test_fetch_and_parse(self) -> None: ...

class TestPerformance:
    def test_normalize_cik_fast(self) -> None: ...
    def test_parse_large_document(self) -> None: ...

class TestErrorHandling:
    def test_error_messages_descriptive(self) -> None: ...
    def test_validation_errors(self) -> None: ...

class TestModuleMetadata:
    def test_module_has_version(self) -> None: ...
    def test_module_has_author(self) -> None: ...
