from sec_nlp.core.enums import FilingMode as FilingMode

def test_enum_values_are_expected() -> None: ...
def test_form_property_returns_correct_form_codes() -> None: ...
def test_form_property_consistency(mode: FilingMode, expected: str) -> None: ...
def test_enum_string_behavior() -> None: ...
def test_invalid_enum_access_raises() -> None: ...
