import logging
from pathlib import Path
from types import TracebackType
from typing import Literal, TextIO

from _typeshed import Incomplete

class TqdmLoggingHandler(logging.StreamHandler[TextIO]):
    def emit(self, record: logging.LogRecord) -> None: ...

class ColoredFormatter(logging.Formatter):
    COLORS: dict[str, str]
    TIME_COLOR: str
    ICONS: dict[str, str]
    RESET: str
    def format(self, record: logging.LogRecord) -> str: ...
    def formatTime(
        self, record: logging.LogRecord, datefmt: str | None = None
    ) -> str: ...

class PaddedFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str: ...

class PaddedColoredFormatter(ColoredFormatter):
    def format(self, record: logging.LogRecord) -> str: ...

def get_timestamped_log_path(
    prefix: str = "run_log", ext: str = ".log"
) -> Path: ...
def setup_logging(
    level: str | int = "INFO",
    format_type: Literal["simple", "detailed", "json"] = "detailed",
    log_file: Path | str | None = None,
    enable_colors: bool = True,
) -> logging.Logger: ...

class LogContext:
    logger: Incomplete
    level: Incomplete
    original_level: Incomplete
    def __init__(
        self, logger: logging.Logger | str, level: str | int
    ) -> None: ...
    def __enter__(self) -> logging.Logger: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

logger: logging.Logger

def color_text(text: str, *, color: str) -> str: ...
def styled_divider(
    char: str = "─", length: int = 50, color: str = "cyan"
) -> str: ...
def styled_title(title: str, color: str = "magenta") -> str: ...
def divider_line(length: int = 70, color: str = "cyan") -> str: ...
def log_divider(
    logger: logging.Logger, length: int = 70, color: str = "cyan"
) -> None: ...
def add_padding_lines(lines: list[str], padding: int = 1) -> list[str]: ...
def styled_header(
    title: str, *, subtitle: str | None = None, width: int = 64
) -> str: ...
def bullet_line(
    label: str,
    value: str | None = None,
    *,
    color: str = "blue",
    icon: str = "➜",
) -> str: ...
def badge(text: str, *, color: str = "magenta") -> str: ...
def success(message: str, *, icon: str = "✓") -> str: ...
def warning(message: str, *, icon: str = "⚠") -> str: ...
def error(message: str, *, icon: str = "✗") -> str: ...
def info_line(
    label: str, value: str | None = None, *, dim: bool = False
) -> str: ...
def format_path(path: str | Path, *, color: str = "blue") -> str: ...
def format_number(num: int | float, *, color: str = "magenta") -> str: ...
def format_size(size_bytes: int | float, *, color: str = "magenta") -> str: ...
def get_logger(name: str | None = None) -> logging.Logger: ...
